### ISSUE TITLE
Connections are not closed properly

### ISSUE THREAD

**Issue by clemensbartz** [clemensbartz/hsql-database-manager-fx8#2]
Although connection.close() is called and all record sets are closed, the lock for the database is not released.

**Comment by Syquel** [comment]
Could you take a look into 56057c97a9ddc87b73c1d7d295a008b784234978 ? This should be in the right direction, but it isn't perfect.

**Comment by clemensbartz** [comment]
I think the _destroy_ method is redundant in this context as the locks are released when the application is stopped. Now, you could argue that it is better for the overall application but I would put that into another ticket.

I am not sure whether I want to enable the **SHUTDOWN** method:
- It is not used in the original database manager implementation which closes connections correctly (although only managing one connection at a time).
- It might be difficult to use the UI for other DBMS later since **SHUTDOWN** is implementation-specific.

**Comment by clemensbartz** [comment]
Updated my comment from earlier: This problem also exists in the original database manager implementation.

Steps to reproduce the issue:

# Open DatabaseManagerSwing1
# Open a file-based database
# Open DatabaseManagerSwing2
# Try to open the same file-based database in DatabaseManagerSwing2 (you get an error)
# In DatabaseManagerSwing1: open memory-based database
# Try to open the file-based database in DatabaseManagerSwing2 now, you will get an error.

**Comment by clemensbartz** [comment]
This seems to be a feature of HSQL:

> Databases are not closed when the last connection to the database is explicitly closed via JDBC. A connection property, shutdown=true, can be specified on the first connection to the database (the connection that opens the database) to force a shutdown when the last connection closes.
> - http://hsqldb.org/doc/guide/running-chapt.html#rgc_closing_db

**Comment by Syquel** [comment]
Yeah, this is exactly what I was going to reply to you :smile: 
The Documentation states (http://hsqldb.org/doc/guide/dbproperties-chapt.html) that the shutdown property should only be used in testing environments or environments which prevent a normal shutdown. Therefore we should issue a SHUTDOWN query to the database upon closing.

There were multiple issues with your former code
First: you issued a "System.exit(0)" in the "onExitAction" which prevented a proper cleanup of resources.
Second: You did not actually close the connections before terminating the Application. Therefore I introduced the destroy method and resource-management.

**Comment by clemensbartz** [comment]
Commit has been cherry picked into the release branch.
